In [1]:
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [2]:
wine = load_wine()

In [3]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [4]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [5]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [6]:
wine_df = pd.DataFrame(data=wine.data,columns=wine.feature_names)

In [7]:
wine_df.shape

(178, 13)

In [8]:
wine_df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [9]:
wine_df.isna().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [10]:
wine_df['target'] = wine.target

In [11]:
wine_df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [12]:
x = wine_df.drop(labels = 'target',axis = 1)

In [13]:
y = wine_df['target']

In [14]:
x

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [15]:
y

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int64

In [69]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

## data before standradisation

In [70]:
model = KNeighborsClassifier(n_neighbors=5)

In [71]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [72]:
y_pred_train = model.predict(x_train)

In [73]:
accuracy_score(y_train,y_pred_train)

0.7535211267605634

In [74]:
y_pred_test = model.predict(x_test)

In [75]:
accuracy_score(y_test,y_pred_test)

0.7222222222222222

In [76]:
confusion_matrix(y_train,y_pred_train)

array([[42,  1,  2],
       [ 7, 36, 14],
       [ 2,  9, 29]])

In [77]:
confusion_matrix(y_test,y_pred_test)

array([[12,  0,  2],
       [ 0, 11,  3],
       [ 2,  3,  3]])

# data after standaradisation

## z = (x−μ)/σ 

## The range of std scaler is -3 to +3

## Real-time Example (articulation):

"Suppose I’m building a credit risk model using customer income (in lakhs) and age (in years). If I don’t scale, income will dominate the model because of its larger range. By using Standard Scaler, both features are normalized, allowing the model to treat them fairly."

## One-liner for interviews:

“We use Standard Scaler to standardize features to zero mean and unit variance, ensuring fair comparison in distance-based models and faster convergence in gradient-based models.”

In [82]:
from sklearn.preprocessing import StandardScaler

In [83]:
std_scale = StandardScaler()

In [84]:
scaled_x = std_scale.fit_transform(x)

In [85]:
x_train,x_test,y_train,y_test = train_test_split(scaled_x,y,train_size=0.8,random_state=42)

In [96]:
model_std = KNeighborsClassifier(n_neighbors=7)
model_std.fit(x_train,y_train)
y_pred_train_std = model_std.predict(x_train)
print(accuracy_score(y_train,y_pred_train_std))
print(confusion_matrix(y_train,y_pred_train_std))


0.971830985915493
[[45  0  0]
 [ 2 53  2]
 [ 0  0 40]]


In [97]:
y_pred_test_std = model_std.predict(x_test)
print(accuracy_score(y_test,y_pred_test_std))
print(confusion_matrix(y_test,y_pred_test_std))

0.9444444444444444
[[14  0  0]
 [ 1 12  1]
 [ 0  0  8]]


# Finding best parameters using grid search cv

In [90]:
from sklearn.model_selection import GridSearchCV

In [106]:
param_grid = {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13]}

In [107]:
cv = GridSearchCV(estimator = model_std, param_grid = param_grid,cv = 2)
cv.fit(x_train,y_train)

GridSearchCV(cv=2, estimator=KNeighborsClassifier(n_neighbors=7),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         13]})

In [108]:
cv.best_score_

np.float64(0.9507042253521126)

In [109]:
cv.best_params_

{'n_neighbors': 7}

# Finding the best accuracy score using for loop


In [125]:
acc = 0
for i in range(2,30):
    model_std = KNeighborsClassifier(n_neighbors=i)
    model_std.fit(x_train,y_train)
    y_pred_train_std = model_std.predict(x_train)
    print(f'{i}th iteration')
    accuracy = accuracy_score(y_train,y_pred_train_std)
    print(accuracy)
    print(confusion_matrix(y_train,y_pred_train_std))
    print('---------------------------')
    if acc < accuracy:
        acc = accuracy

print(f'The maximum accuracy is {acc}')
    




2th iteration
0.971830985915493
[[45  0  0]
 [ 4 53  0]
 [ 0  0 40]]
---------------------------
3th iteration
0.9577464788732394
[[45  0  0]
 [ 3 51  3]
 [ 0  0 40]]
---------------------------
4th iteration
0.971830985915493
[[45  0  0]
 [ 3 53  1]
 [ 0  0 40]]
---------------------------
5th iteration
0.9859154929577465
[[45  0  0]
 [ 1 55  1]
 [ 0  0 40]]
---------------------------
6th iteration
0.971830985915493
[[45  0  0]
 [ 3 53  1]
 [ 0  0 40]]
---------------------------
7th iteration
0.971830985915493
[[45  0  0]
 [ 2 53  2]
 [ 0  0 40]]
---------------------------
8th iteration
0.971830985915493
[[45  0  0]
 [ 3 53  1]
 [ 0  0 40]]
---------------------------
9th iteration
0.9788732394366197
[[45  0  0]
 [ 2 54  1]
 [ 0  0 40]]
---------------------------
10th iteration
0.9859154929577465
[[45  0  0]
 [ 2 55  0]
 [ 0  0 40]]
---------------------------
11th iteration
0.9788732394366197
[[45  0  0]
 [ 2 54  1]
 [ 0  0 40]]
---------------------------
12th iteration
0.978873