In [35]:
pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [36]:
import numpy as np

In [37]:
arr = np.array([10,20,30,40,50,60])

In [38]:
type(arr)


numpy.ndarray

In [39]:
arr+2

array([12, 22, 32, 42, 52, 62])

In [40]:
arr-2

array([ 8, 18, 28, 38, 48, 58])

In [41]:
num = np.array([10,20,30.1,40])

In [42]:
num

array([10. , 20. , 30.1, 40. ])

In [43]:
num_1 = np.array([10,20,30,'40'])

In [44]:
num_1

array(['10', '20', '30', '40'], dtype='<U21')

## create 2D array


In [51]:
num_2 = np.array([[1,2,3.5,4],[5,6,7,8],[9,10,11,12]])

In [52]:
num_2.ndim 

2

In [53]:
num_2

array([[ 1. ,  2. ,  3.5,  4. ],
       [ 5. ,  6. ,  7. ,  8. ],
       [ 9. , 10. , 11. , 12. ]])

In [54]:
num_2[0][2]

np.float64(3.5)

In [57]:
num_2[1][2]=3.2

In [58]:
num_2

array([[ 1. ,  2. ,  3.5,  4. ],
       [ 5. ,  6. ,  3.2,  8. ],
       [ 9. , 10. , 11. , 12. ]])

In [59]:
num_2[1][2] = np.nan

In [61]:
num_2

array([[ 1. ,  2. ,  3.5,  4. ],
       [ 5. ,  6. ,  nan,  8. ],
       [ 9. , 10. , 11. , 12. ]])

## creating 3d array

In [62]:
num_3 = np.array([[[0,1,2],[3,4,5],[6,7,8],[9,10,11]]])

In [63]:
num_3.ndim

3