In [1]:
import pandas as pd

In [19]:
# TFidf used to convert words to numerical form
from sklearn.feature_extraction.text import TfidfVectorizer
# linear kernel is used to calculate the similarity between/w tfidf vectors
from sklearn.metrics.pairwise import linear_kernel
import numpy as np

In [6]:
movie = pd.read_csv('Movies_dataset.csv')

In [7]:
movie

Movie Title  Ratinng                     genre  \
0             3 Idiots      8.4             Comedy, Drama   
1     Taare Zameen Par      8.3             Drama, Family   
2                   PK      8.1     Comedy, Drama, Sci-Fi   
3               Dangal      8.3  Action, Biography, Drama   
4      Rang De Basanti      8.1      Comedy, Crime, Drama   
..                 ...      ...                       ...   
806   Parde Ke Peechey      5.9                    Action   
807            Dhamkee      4.0            Action, Comedy   
808       Chhoo Mantar      6.0                    Comedy   
809  Ladki Sahyadri Ki      5.0            Musical, Drama   
810          Madadgaar      7.2            Drama, Romance   

                                                   act  \
0    Aamir Khan, Madhavan, Mona Singh, Sharman Josh...   
1    Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...   
2    Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...   
3    Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   
4    Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...   
..                                                 ...   
806  Vinod Mehra, Yogeeta Bali, Pran Sikand, Bindu ...   
807  Ravi Teja, Anushka Shetty, Krishna, Pradeep Si...   
808  Shyama, Johnny Walker, Anita Guha, Gajanan Jag...   
809  Shalini Abhyankar, Keshavrao Date, Vatsala Des...   
810  Ravindra Kapoor, Indira, Jeevan Dhar, Uma Dutt...   

                                                  Plot  
0    papadum, hairy chest, against the system, comi...  
1    teacher student relationship, dyslexia, agains...  
2    guru, religion, tv reporter, alien on earth, p...  
3    small town, father daughter relationship, male...  
4    delhi india, murder, friend, india, awakening,...  
..                                                 ...  
806                                              crook  
807                                              sorry  
808  rescue, beating, river, village, wedding, flir...  
809                                              sorry  
810                                              sorry  

[811 rows x 5 columns]

In [8]:
movie.isna().sum()

Movie Title    0
Ratinng        0
genre          0
act            0
Plot           0
dtype: int64

In [9]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Movie Title  811 non-null    object 
 1   Ratinng      811 non-null    float64
 2   genre        811 non-null    object 
 3   act          811 non-null    object 
 4   Plot         811 non-null    object 
dtypes: float64(1), object(4)
memory usage: 31.8+ KB


In [10]:
movie.describe(include = 'all')

Movie Title     Ratinng                 genre    act   Plot
count          811  811.000000                   811    811    811
unique         811         NaN                   144    781    663
top       3 Idiots         NaN  Action, Crime, Drama  sorry  sorry
freq             1         NaN                    60     30     87
mean           NaN    5.868927                   NaN    NaN    NaN
std            NaN    1.819380                   NaN    NaN    NaN
min            NaN    0.000000                   NaN    NaN    NaN
25%            NaN    5.000000                   NaN    NaN    NaN
50%            NaN    6.200000                   NaN    NaN    NaN
75%            NaN    7.200000                   NaN    NaN    NaN
max            NaN    8.900000                   NaN    NaN    NaN

In [11]:
tfidf =  TfidfVectorizer()

In [17]:
genre_tranform = tfidf.fit_transform(movie['genre'])

In [20]:
# with help of toarrary() we can see the values which we converted with the help of tdidf
genre_tranform[2].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.23854688,
        0.        , 0.        , 0.15553797, 0.        , 0.        ,
        0.67782864, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.67782864, 0.        , 0.        ,
        0.        , 0.        ]])

In [21]:
genre_tranform[24].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24385665, 0.71267675, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.65774295,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [22]:
indexed=pd.Series(index=movie["Movie Title"],data=movie.index)

In [23]:
indexed

Movie Title
3 Idiots               0
Taare Zameen Par       1
PK                     2
Dangal                 3
Rang De Basanti        4
                    ... 
Parde Ke Peechey     806
Dhamkee              807
Chhoo Mantar         808
Ladki Sahyadri Ki    809
Madadgaar            810
Length: 811, dtype: int64

In [24]:
indexed['Dangal']

np.int64(3)

In [49]:
linear_genre = linear_kernel(genre_tranform[3],genre_tranform)

In [50]:
linear_genre

array([[0.14539681, 0.08618264, 0.04140535, 1.        , 0.09990682,
        0.13589812, 0.21733574, 0.05341721, 0.14539681, 0.17233413,
        0.10700303, 0.08165956, 0.13589812, 0.08165956, 0.27544293,
        0.60083646, 0.        , 0.        , 0.21845665, 0.26620732,
        0.18877571, 0.3367974 , 0.08478273, 0.23004049, 0.06491643,
        0.17233413, 0.08165956, 0.13589812, 0.10700303, 0.83228247,
        0.07985771, 0.06402653, 0.30856288, 0.3367974 , 0.        ,
        0.09029178, 0.37558105, 0.21845665, 0.07985771, 0.13589812,
        0.07719124, 0.18877571, 0.85005256, 0.37558105, 0.60083646,
        0.21845665, 0.21845665, 0.13589812, 0.16931566, 0.07585749,
        0.21733574, 0.14539681, 0.10700303, 0.07985771, 0.21733574,
        0.13589812, 0.05648666, 0.06382818, 0.07677444, 0.12217443,
        0.30856288, 0.3367974 , 0.06314687, 0.14539681, 0.36062726,
        0.08478273, 0.07719124, 0.36062726, 0.30856288, 0.10700303,
        0.3367974 , 0.26620732, 0.10700303, 0.15

In [51]:
scores=pd.DataFrame(linear_genre).T

In [52]:
scores

0
0    0.145397
1    0.086183
2    0.041405
3    1.000000
4    0.099907
..        ...
806  0.410425
807  0.290974
808  0.000000
809  0.092540
810  0.135898

[811 rows x 1 columns]

In [53]:
scores.columns=["score"]

In [54]:
scores

score
0    0.145397
1    0.086183
2    0.041405
3    1.000000
4    0.099907
..        ...
806  0.410425
807  0.290974
808  0.000000
809  0.092540
810  0.135898

[811 rows x 1 columns]

In [55]:
soreted_Score = scores.sort_values(by = 'score',ascending=False)

In [56]:
soreted_Score

score
3    1.000000
174  1.000000
116  1.000000
196  1.000000
415  0.911894
..        ...
409  0.000000
408  0.000000
637  0.000000
641  0.000000
346  0.000000

[811 rows x 1 columns]

In [57]:
movie

Movie Title  Ratinng                     genre  \
0             3 Idiots      8.4             Comedy, Drama   
1     Taare Zameen Par      8.3             Drama, Family   
2                   PK      8.1     Comedy, Drama, Sci-Fi   
3               Dangal      8.3  Action, Biography, Drama   
4      Rang De Basanti      8.1      Comedy, Crime, Drama   
..                 ...      ...                       ...   
806   Parde Ke Peechey      5.9                    Action   
807            Dhamkee      4.0            Action, Comedy   
808       Chhoo Mantar      6.0                    Comedy   
809  Ladki Sahyadri Ki      5.0            Musical, Drama   
810          Madadgaar      7.2            Drama, Romance   

                                                   act  \
0    Aamir Khan, Madhavan, Mona Singh, Sharman Josh...   
1    Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...   
2    Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...   
3    Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   
4    Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...   
..                                                 ...   
806  Vinod Mehra, Yogeeta Bali, Pran Sikand, Bindu ...   
807  Ravi Teja, Anushka Shetty, Krishna, Pradeep Si...   
808  Shyama, Johnny Walker, Anita Guha, Gajanan Jag...   
809  Shalini Abhyankar, Keshavrao Date, Vatsala Des...   
810  Ravindra Kapoor, Indira, Jeevan Dhar, Uma Dutt...   

                                                  Plot  
0    papadum, hairy chest, against the system, comi...  
1    teacher student relationship, dyslexia, agains...  
2    guru, religion, tv reporter, alien on earth, p...  
3    small town, father daughter relationship, male...  
4    delhi india, murder, friend, india, awakening,...  
..                                                 ...  
806                                              crook  
807                                              sorry  
808  rescue, beating, river, village, wedding, flir...  
809                                              sorry  
810                                              sorry  

[811 rows x 5 columns]

In [59]:
indexed[indexed == 174]

Movie Title
Mary Kom    174
dtype: int64

In [60]:
indexed[indexed == 116]

Movie Title
The Legend of Bhagat Singh    116
dtype: int64

## Conclusion:

## if the user watching 'Dangal' we can recommend 'Mary Kom' and 'The legend of Bhagat Singh'

# now we create a function to recommend the movie for the user


In [86]:
def movie_rec(name,n):
    linear_value = linear_kernel(genre_tranform[indexed[name]],genre_tranform)
    scores=pd.DataFrame(linear_value).T
    scores.columns=["score"]
    score = scores.sort_values(by = 'score',ascending=False)

    list_movie = []
    for i in range(0,n+1):
        s = {'Movie name': movie['Movie Title'][score.index[i]],
             'Ratinng': movie['Ratinng'][score.index[i]],
             'genre': movie['genre'][score.index[i]],
             'act': movie['act'][score.index[i]]
             }
        list_movie.append(s)
    return list_movie
    

In [87]:
user1 = pd.DataFrame(movie_rec('Dangal',10))
user1


Movie name  Ratinng                     genre  \
0                             Dangal      8.3  Action, Biography, Drama   
1                           Mary Kom      6.8  Action, Biography, Drama   
2         The Legend of Bhagat Singh      8.1  Action, Biography, Drama   
3   Manikarnika: The Queen of Jhansi      6.4  Action, Biography, Drama   
4                     Saand Ki Aankh      7.7          Biography, Drama   
5                            Mastram      4.8          Biography, Drama   
6                             Shahid      8.2          Biography, Drama   
7      The Accidental Prime Minister      6.0          Biography, Drama   
8                           Super 30      7.9          Biography, Drama   
9                            Aligarh      7.8          Biography, Drama   
10                  PM Narendra Modi      2.9          Biography, Drama   

                                                  act  
0   Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...  
1   Priyanka Chopra Jonas, Sunil Thapa, Robin Das,...  
2   Ajay Devgn, Sushant Singh, D. Santosh, Akhilen...  
3   Kangana Ranaut, Danny Denzongpa, Suresh Oberoi...  
4   Taapsee Pannu, Bhumi Pednekar, Prakash Jha, Vi...  
5   Rahul Bagga, Tara-Alisha Berry, Aakash Dahiya,...  
6   Rajkummar Rao, Prabhleen Sandhu, Mohd. Zeeshan...  
7   Anupam Kher, Akshaye Khanna, Suzanne Bernert, ...  
8   Hrithik Roshan, Mrunal Thakur, Nandish Singh S...  
9   Manoj Bajpayee, Rajkummar Rao, Ashish Vidyarth...  
10  Vivek Oberoi, Manoj Joshi, Darshan Kumaar, Anj...

In [88]:
user2 = pd.DataFrame(movie_rec('Taare Zameen Par',10))
user2


Movie name  Ratinng                  genre  \
0             Anand Ashram      7.3          Drama, Family   
1                 Dear Dad      6.2          Drama, Family   
2                Gangoobai      7.6          Drama, Family   
3              Chhoti Bahu      5.8          Drama, Family   
4                 Kaamchor      6.5          Drama, Family   
5         Taare Zameen Par      8.3          Drama, Family   
6         Jai Santoshi Maa      7.2          Drama, Family   
7                  Amanush      7.0          Drama, Family   
8      Raampur Ka Lakshman      6.5          Drama, Family   
9       Nil Battey Sannata      8.2          Drama, Family   
10  Mere Brother Ki Dulhan      5.9  Comedy, Drama, Family   

                                                  act  
0   Ashok Kumar, Uttam Kumar, Sharmila Tagore, Rak...  
1   Arvind Swamy, Ekavali Khanna, Himanshu Sharma,...  
2   Sarita Joshi, Purab Kohli, Mita Vashisht, Raj ...  
3   Vikas Anand, Beena Banerjee, Bindu Desai, Avta...  
4   Rakesh Roshan, Jaya Prada, Tanuja Samarth, Suj...  
5   Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...  
6   Nushrratt Bharuccha, Lalit Tiwari, Sanjay Swar...  
7   Uttam Kumar, Sharmila Tagore, Prema Narayan, A...  
8   Randhir Kapoor, Rekha, Shatrughan Sinha, Padma...  
9   Swara Bhaskar, Abhinay Raj Singh, Ratna Pathak...  
10  Imran Khan, Katrina Kaif, Ali Zafar, Tara D'So...

In [89]:
user3 = pd.DataFrame(movie_rec("Munna Bhai M.B.B.S.",5))

In [90]:
user3

Movie name  Ratinng          genre  \
0                  3 Idiots      8.4  Comedy, Drama   
1           Malamaal Weekly      6.9  Comedy, Drama   
2                 Jolly LLB      7.5  Comedy, Drama   
3              Badle Ki Aag      4.3  Comedy, Drama   
4               Dasvidaniya      7.8  Comedy, Drama   
5  Lipstick Under My Burkha      6.8  Comedy, Drama   

                                                 act  
0  Aamir Khan, Madhavan, Mona Singh, Sharman Josh...  
1  Paresh Rawal, Om Puri, Riteish Deshmukh, Reema...  
2  Arshad Warsi, Amrita Rao, Boman Irani, Saurabh...  
3  Brahmanandam, Charan, Prabhu Deva, Charmme Kau...  
4  Vinay Pathak, Sarita Joshi, Rajat Kapoor, Saur...  
5  Aahana Kumra, Ratna Pathak Shah, Konkona Sen S...